sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "woodydocker_2"
  env: "Woodydocker_2-env"
  bucket_name: "elasticbeanstalk-us-west-2-255107891704"
  bucket_path: "woodydocker_2"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key
